architect: extsoft
docker:
    image: extsoft/rultor-runtime:r24b04p0
    as_root: true
merge:
    fast-forward: only
    rebase: true
    script: |-
        bats $PWD
        pdd --source=$(pwd) --verbose --file=/dev/null
release:
    script: |-
        echo "Release ${tag}"
        bats $PWD
