architect: extsoft
docker:
    image: beeshive/elegant-git-ci:4
    as_root: true
merge:
    fast-forward: only
    rebase: true
    script: .workflows/ci-pipeline.bash testing
release:
    script: |-
        .workflows/ci-pipeline.bash testing
        echo "Release ${tag}"
